### ISSUE TITLE
Is linked k8s issue correct?

### ISSUE THREAD

**Issue by vdice** [deis/workflow-migration#7]
The README links to the following kubernetes issue https://github.com/kubernetes/kubernetes/pull/35071 in Step 2 under `Usage`.  Is this the issue intended?  If so, it has been merged/closed -- therefore, does it still affect this tool?

**Comment by vdice** [comment]
Ah, if so, appears it is in k8s >= 1.5.0

**Comment by bacongobbler** [comment]
I believe the reason why we need to save the controller and registry deployment when migrating is due to that change. The migration may not complete in its entirety if you're using an older version of k8s which does not contain that change, as far as I understand the issue.

https://github.com/deis/workflow-migration/commit/44164ab68e562c93a207f7c2f99cf31ac67c576f introduced this tidbit. @kmala, does this step only apply to clusters older than v1.5.1?

**Comment by kmala** [comment]
that step of copying is needed for all clusters because the migration job is deleting the controller and registry deployments for all clusters https://github.com/deis/workflow-migration/blob/master/boot.go#L92 but the code is present in order to support older clusters

**Comment by bacongobbler** [comment]
perhaps ^^ is the cause for #6. Gonna have to dive into the code.

Anyways, sounds like this is intentional for now and no further action is required
